import os
i = 0
while i <= 10:
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  os.system("explorer.exe")
  
  
